### ISSUE TITLE
Where are the unbundled files & how are they bundled

### ISSUE THREAD

**Issue by tcyrus** [gwroblew/Quantum-Computing-Playground#3]
Where are the unbundled js and css files. `css/codemirror-bundle.css`, `js/bootstrap_js-bundle.js`, `js/codemirror-bundle.js`, `js/jquery-bundle.js`, and `js/threejs-bundle.js` are bundled together using files not present in the repo. There also is no documentation on how these files are bundled together.

**Comment by gwroblew** [comment]
The unbundled files are completely redundant: the bundles are concatenated bunches of files, with headers in the form like:

//third_party/javascript/jquery/v2_0_3/jquery-2.0.3.min.js

so it is obvious which versions of the libraries the files come from.
